import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TopBar } from "@/components/layout/TopBar";
import { BottomNav } from "@/components/layout/BottomNav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className="max-w-[390px] mx-auto min-h-screen bg-[#09090b] shadow-2xl shadow-indigo-500/10 overflow-x-hidden relative flex flex-col selection:bg-indigo-500/30">
          
          {/* Premium Ambient Background */}
          <div className="fixed inset-0 z-0 pointer-events-none flex justify-center">
            <div className="absolute top-[-10%] w-[500px] h-[500px] bg-indigo-500/10 blur-[100px] rounded-full mix-blend-screen" />
            <div className="absolute bottom-[-10%] w-[400px] h-[400px] bg-fuchsia-500/10 blur-[100px] rounded-full mix-blend-screen" />
          </div>

          <div className="relative z-10 flex flex-col flex-1">
            <TopBar />
            <main className="flex-1 pb-24">
              {children}
            </main>
            <BottomNav />
          </div>
        </div>
      </body>
    </html>
  );
}
